### ISSUE TITLE
Look into replacing activity web job with Kusto query

### ISSUE THREAD

**Issue by antross** [webhintio/telemetry#20]
Originally I didn't think this would be possible. As I've been digging into Kusto more, though, I think we can potentially query 28-day retention from the raw activity entries directly. This would likely involve multiple queries, using the [`materialize`](https://docs.microsoft.com/en-us/azure/kusto/query/materializefunction) function to re-use results. Also [`extract-all`](https://docs.microsoft.com/en-us/azure/kusto/query/extractallfunction) may be useful to break apart the activity history strings for further processing.

**Comment by molant** [comment]
@antross @sarvaje do we still need this? I think you succeeded in implementing it, right?

**Comment by antross** [comment]
Yes, and it ended up being MUCH simpler than I suspected.
